### ISSUE TITLE
NPE when trying to run example (examples/src/main/kotlin/table/BasicTable.kt) from idea

### ISSUE THREAD

**Issue by y9Kap** [mipt-npm/plotly.kt#106]
The error appears due to the lack of a plotly.min.js resource

**Comment by SPC-code** [comment]
Thank you, it seems like the problem was introduced around 0.7.0. The name of the resource changed. I will fix it shortly.

**Comment by SPC-code** [comment]
Thank you again for your report. Fix was published at https://github.com/SciProgCentre/plotly.kt/releases/tag/v0.7.1.1 and already available on repo.kotlin.link. 

Further changes will be included in version 0.8 and will be maintained in https://github.com/SciProgCentre/visionforge repository.
