### ISSUE TITLE
Unmaintained dependencies

### ISSUE THREAD

**Issue by bjonnh** [mipt-npm/plotly.kt#18]
I get the warning: 
warning workspace-aggregator-6ad3d204-022c-4712-bd57-40e22af0df44 > plotly.kt-plotlykt-core > text-encoding@0.7.0: no longer maintained

not sure if it is important or not.

**Comment by altavir** [comment]
It is an issue from kotlinx-io: https://github.com/Kotlin/kotlinx-io/issues/57. I had to manually add dependency to make it work. I will leave it here to track.

Actually, we do not use io right now, all serialization is done via ktor. I will consider removing it.

**Comment by altavir** [comment]
Probably won't fix since there are more those warnings from the upstream each month.
