### ISSUE TITLE
Plotly specific meta delegate

### ISSUE THREAD

**Issue by Zelenyy** [mipt-npm/plotly.kt#21]
Create or adjust meta delegate for plotly types.

List of plotly types:

- data_array --- An {array} of data. The value MUST be an {array}, or we ignore it. Note that typed arrays (e.g. Float32Array) are supported.
- enumerated --- Enumerated value type. The available values are listed in `values`.
- boolean --- A boolean (true/false) value.
- number --- A number or a numeric value (e.g. a number inside a string). When applicable, values greater (less) than `max` (`min`) are coerced to the `dflt`.
- integer --- An integer or an integer inside a string. When applicable, values greater (less) than `max` (`min`) are coerced to the `dflt`.
- string --- A string value. Numbers are converted to strings except for attributes with `strict` set to true.
- color --- A string describing color. Supported formats: - hex (e.g. '#d3d3d3') - rgb (e.g. 'rgb(255, 0, 0)') - rgba (e.g. 'rgb(255, 0, 0, 0.5)') - hsl (e.g. 'hsl(0, 100%, 50%)') - hsv (e.g. 'hsv(0, 100%, 100%)') - named colors (full list: http://www.w3.org/TR/css3-color/#svg-color)
- colorlist --- A list of colors. Must be an {array} containing valid colors.
- colorscale --- A Plotly colorscale either picked by a name: (any of Greys, YlGnBu, Greens, YlOrRd, Bluered, RdBu, Reds, Blues, Picnic, Rainbow, Portland, Jet, Hot, Blackbody, Earth, Electric, Viridis, Cividis ) customized as an {array} of 2-element {arrays} where the first element is the normalized color level value (starting at *0* and ending at *1*), and the second item is a valid color string.
- angle --- A number (in degree) between -180 and 180.
- subplotid --- An id string of a subplot type (given by dflt), optionally followed by an integer >1. e.g. if dflt='geo', we can have 'geo', 'geo2', 'geo3', ...
- flaglist --- A string representing a combination of flags (order does not matter here). Combine any of the available `flags` with *+*. (e.g. ('lines+markers')). Values in `extras` cannot be combined.
- any --- Any type.
- info_array --- An {array} of plot information.

**Comment by altavir** [comment]
Some delegates are here: https://github.com/mipt-npm/plotly.kt/blob/dev/plotlykt-core/src/commonMain/kotlin/scientifik/plotly/dfExt.kt
