### ISSUE TITLE
Self-contained HTML files

### ISSUE THREAD

**Issue by dector** [mipt-npm/plotly.kt#24]
Right now some HTML file assets are loaded from the Internet.

I can implement solution for building self-contained HTML files for offline use.

**Comment by altavir** [comment]
It would be nice. I thought about that just today. We can add a flag for that in 'writeFile' options.

**Comment by dector** [comment]
Nice. Will try to create PR this week

**Comment by altavir** [comment]
It seems like self-contained html weight too much. Maybe it is better to download js and put it into the same directory. This way several plots could share it.

**Comment by altavir** [comment]
Done via 1531db288309289a870515d66a31dc5e79591195
