### ISSUE TITLE
Implement `Offline` assets providing type

### ISSUE THREAD

**Issue by dector** [mipt-npm/plotly.kt#25]
This is follow-up issue for #24.

`Offline` mode means that assets will be downloaded, stored in a separate folder and referenced from HTML files using relative path.

**Comment by altavir** [comment]
Thanks a lot! I will review it ASAP.

**Comment by altavir** [comment]
It seems like plotly for python does it the same way: https://github.com/plotly/plotly.py/blob/8bf3d5e8bfc212e4df486136d00ba109c78c3945/packages/python/plotly/plotly/offline/offline.py#L459

**Comment by altavir** [comment]
Mostly done via 1531db288309289a870515d66a31dc5e79591195. Needs to be documented though. Currently, it works for HTML headers. I don't know if we need it for other assets.

**Comment by altavir** [comment]
@dector Should we close this? The solution right now is much more narrow than the one, you proposed. Should we expand custom content support?

**Comment by dector** [comment]
I agree. We can do this later if needed.
