### ISSUE TITLE
Add JavaFX back-end

### ISSUE THREAD

**Issue by altavir** [mipt-npm/plotly.kt#5]
Requires #4 to properly use JavaFX tabs.

**Comment by natanfudge** [comment]
I think you should take a look at [Jetpack Compose](https://developer.android.com/jetpack/compose). It's not near ready or compatible with platforms other than Android right now, but it could be ported to other platforms in the future. 
Some discussion in the data2viz forums: https://forum.data2viz.io/t/jetpack-compose-and-data2viz/74

**Comment by altavir** [comment]
@natanfudge I do not plan to support Android in near future. I think the web-front will suffice for it. Using Jetpack just to run the browser inside it seems to be an overkill.

**Comment by altavir** [comment]
Currently implemented in dev branch. There is still a problem with dynamic updated. FX browser seem to break ktor websockects: https://github.com/ktorio/ktor/issues/1275
