### ISSUE TITLE
Fix kotlin-logging dependency

### ISSUE THREAD

**Issue by altavir** [mipt-npm/plotly.kt#66]
Wait for https://github.com/MicroUtils/kotlin-logging/issues/153 or drop kotlin-logging completely for native targets.

**Comment by luispollo** [comment]
I believe I just ran into this in a JVM project. Gradle log shows:
```
Resolution rules could not resolve all dependencies to align configuration ':keel-netflix:compileClasspath':
 - io.github.microutils:kotlin-logging:1.4.4 -> io.github.microutils:kotlin-logging:1.9.0-dev-npm-2 - Could not find io.github.microutils:kotlin-logging:1.9.0-dev-npm-2.
```
Is there a workaround?

**Comment by luispollo** [comment]
If anyone else comes across this, I was able to force the lib version to work around the problem:
```groovy
configurations.all {
  resolutionStrategy {
    force("io.github.microutils:kotlin-logging:1.4.4")
  }
}
```

**Comment by altavir** [comment]
@luispollo thanks for the comment. The problem is that kotlin-loggint does not publish all required artifacts for kotlin-native so we replaced it with our own fork which is placed in `maven("https://dl.bintray.com/mipt-npm/dev")` repository. You can just add it to the repository list and everything will be working, but if you work production repository, you miss that. I've placed a notice about that in `Readme` recently.

The problem is already fixed in the upstream `dataforge` project via removing kotlin-logging from the core. I will review the changes and update everything soon.

**Comment by altavir** [comment]
Here is the [readme section](https://github.com/mipt-npm/plotly.kt#build-and-usage).

**Comment by altavir** [comment]
Removed in 0.4.0
