### ISSUE TITLE
Gradle: Could not resolve kscience.plotlykt...

### ISSUE THREAD

**Issue by dosier** [mipt-npm/plotly.kt#75]
Hey, I am trying to include this project as a dependency, my gradle looks as follows: 
```kotlin
repositories {
    maven("https://repo.kotlin.link")
}
dependencies {
    implementation("kscience.plotlykt:plotlykt-server:0.4.0")
}
```
But gradle cannot find it, giving me the following exception:
> Could not resolve kscience.plotlykt:plotlykt-server:0.4.0.
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Am I missing something? This is for a JVM based project btw.

**Comment by altavir** [comment]
Oops, there is a mistake in readme, it points to the old package. I will fix it right away, meanwhile, it should be `space.kscience:plotlykt-server:0.4.0`.
