### ISSUE TITLE
Failure to resolve dependency to org.jetbrains:kotlin-css-jvm without bintray

### ISSUE THREAD

**Issue by luispollo** [mipt-npm/plotly.kt#76]
Bintray hast been [sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). If you remove the bintray repository, the build fails to resolve the library above. I couldn't not find an alternative artifact repository (tried the one referenced [here](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-css) but it doesn't have the `-jvm` variant.

**Comment by altavir** [comment]
I do not think we have a kotlin-css dependency in this project. Please correct me if I am wrong. The [kotlin-wrappers meta-repository](https://github.com/JetBrains/kotlin-wrappers) that includes kotlinx-css is not published on central yet. One needs to add `maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/kotlin-js-wrappers")` to repositories to make it work.

**Comment by luispollo** [comment]
Indeed, that's what fixed it for me. I was just about to add an update here.

From `gradle dependencyInsight`:
```
org.jetbrains:kotlin-css-jvm:1.0.0-pre.122-kotlin-1.4.10
\--- space.kscience:plotlykt-core-jvm:0.4.0
     \--- space.kscience:plotlykt-server:0.4.0
          \--- default
```

**Comment by altavir** [comment]
Ah, now I see it. I don't believe we need it, so it should be removed. Thanks for the report!

**Comment by altavir** [comment]
Deployed in 0.4.1. It is available on `https://repo.kotlin.link`, but not on central since it is only a minor fix.
