### ISSUE TITLE
Single shape block transforms to object instead of array

### ISSUE THREAD

**Issue by SPC-code** [mipt-npm/plotly.kt#97]
And example could be found in #96

**Comment by SPC-code** [comment]
@Joseph-Hui The problem from #96 is fixed in the dev release `0.6.0-dev-2`. I can't promise it will be released soon to the mavenCentral since it relies on the upstream change on DataForge. But you can use it anyway. I've also added some utility functions to make defining shape rectangle more convenient.

**Comment by Joseph-Hui** [comment]
I just found that `annotation` has the same problem. One `annotation` does not show up.

**Comment by SPC-code** [comment]
Yes, it is the common problem for all blocks. The fix fixes them all.

**Comment by SPC-code** [comment]
Released in 0.6.0
